<a href="https://colab.research.google.com/github/ckokobean/SFUHS-Computational-Modeling-and-Simulation/blob/master/Neural_Networks_Work_along.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Perceptrons 

perceptron=simplest neural network constisting of only one neuron

![alt text](https://s3.amazonaws.com/stackabuse/media/intro-to-neural-networks-scikit-learn-2.png)

one input layor and one neuron

input layer acts as the dendrites and receives the inputs 

at the neuron, the weights are applied and results are added together to get a sum. this sum is passed through the final layer aka an activation function 

activation function (nucleus) processes the sum and yields an output 

# Multilayer Perceptron

an artifical neural network has an input layer, 1+ hidden layers, and an output layer 

![alt text](https://s3.amazonaws.com/stackabuse/media/intro-to-neural-networks-scikit-learn-3.png)

neural network executes in 2 phases:

* feed-forward 
* back propagation



# Feed-forward 

1. values receives in the input layer are multipleid with the weights 

2. each neuron in the first hidden layer receives different values from the input layer depending upon the weights and biases. relu functions are applied to calculate new values for the neurons in the hidden layers, while a sigmoid function is used to the output layer neuron.

3. continue for all hidden layers


# Back propagation 

reconfiguring the weights of the model to refine the algorithm

1. error is calculated by quantifying the differennce between the predicted output and desired output -- loss function

> NOTE: neural networks are ***supervised learning*** algorithms that need the desired outputs for the a given set of inputs, which is what allows it to learn from the data!

2. minimize the loss function. use optimization function to minimize the loss function.

epoch-one cycle of feed-forward and back propagation



In [0]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

# location of dataset
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# assign column names to the dataset 
names = ['sepal-length','sepal-width','petal-length','petal-width','Class']

# read dataset to pandas dataframe 
irisdata=pd.read_csv(url,names=names)

irisdata.head()


sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

task = predict the class that is iris belongs to using the sepal and petal lengths and widths

next step: split our dataset into attributes and labels 

In [0]:
X = irisdata.iloc[:,0:4] # take first four columns

y = irisdata.select_dtypes(include=[object])

In [0]:
y.head()

Class
0  Iris-setosa
1  Iris-setosa
2  Iris-setosa
3  Iris-setosa
4  Iris-setosa

y values are categorical. however, nueral networks work better with numerical data. 

next step: convert these categorical values to numerical values via integer encoding or one-hot encoding 

here, since i only need to convert the outputs to numerical values, we can simply use integer encoding. However, if we needed to convert the ***input*** values to numerical values, would need to use one-hot encoding. 


In [0]:
y.Class.unique()
# we have 3 unique classes 

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [0]:
from sklearn import preprocessing

le = preprocessing.LabelEncoder()

y = y.apply(le.fit_transform)

In [0]:
y.Class.unique()

array([0, 1, 2])

# train test split

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=.2)

# Feature scaling

so that all of them can be uniformly evaluated 


feature scaling is performed only on the training data, not on the test data. in the real world, data is not scaled so try to keep our test data as real as possible.


In [0]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X_train)

X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

# Training and Predictions 

next step: rain a neural network that can actually make predictions


In [0]:
from sklearn.neural_network import MLPClassifier
mlp=MLPClassifier(hidden_layer_sizes=(10,10,10),max_iter=1000) # creates neural network
# hidden_layer_sizes creates 3 layers of 10 nodes each; just try different combos and see what is best
#max_iter = number of iterations of epochs (cycles of feed-forward and back propagation)
mlp.fit(X_train, y_train.values.ravel())

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(10, 10, 10), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=1000,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [0]:
# make predictions to our test data
predictions=mlp.predict(X_test)

# Evaluating the algorithm

using confusion matrix and classification report 


In [0]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,predictions))

[[ 6  0  0]
 [ 0 12  1]
 [ 0  2  9]]


In [0]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       0.86      0.92      0.89        13
           2       0.90      0.82      0.86        11

    accuracy                           0.90        30
   macro avg       0.92      0.91      0.92        30
weighted avg       0.90      0.90      0.90        30



# Conclusion

we can see from the f1 score of 0.97  that the neural network predicts with 97% accuracy.
