<a href="https://colab.research.google.com/github/ckokobean/SFUHS-Computational-Modeling-and-Simulation/blob/master/One_hot_encoding_work_along.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Manual one hot encoding

In [0]:
from numpy import argmax
# define input string
data='hello world'
print(data)
# define universe of possible input values
alphabet = 'abcdefghijklmnopqrstuvwxyz ' # need to put a space after the alphabet
# define a mapping of chars to integers
char_to_int=dict((c,i) for i, c in enumerate(alphabet))
int_to_char=dict((i,c) for i, c in enumerate(alphabet))
# integer encode input data
integer_encoded = [char_to_int[char] for char in data]
print(integer_encoded)

hello world
[7, 4, 11, 11, 14, 26, 22, 14, 17, 11, 3]


In [0]:
# one hot encoding
onehot_encoded=list()
for value in integer_encoded:
  # create an array of 26 zeros
  letter = [0 for _ in range(len(alphabet))]
  letter[value]=1 # for the index number corresponding to the letter , change that 0 --> 1 
  onehot_encoded.append(letter) # add that vector that matches a letter to the onehot_encoding list
print(onehot_encoded)

# onehot_encoded is an array in which each entry corresponds to a letter in the data

[[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]


In [0]:
# invert encoding
inverted = int_to_char[argmax(onehot_encoded[0])]
print(inverted)

# took the 1st entry in onehot_encoded array and turned it from a vector --> letter
# what does argmax do? 

print(argmax(onehot_encoded[0])) # argmax returns the index of the max value! 

h
7


# Using scikit learn library

In [0]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
# define example
data=['cold','cold','warm', 'cold','hot', 'hot', 'warm', 'cold', 'warm', 'hot']
values = array(data)
print(values)

# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)

['cold' 'cold' 'warm' 'cold' 'hot' 'hot' 'warm' 'cold' 'warm' 'hot']
[0 0 2 0 1 1 2 0 2 1]


In [0]:
# binary, one hot encoding 
onehot_encoder = OneHotEncoder(sparse=False) # what is the sparse thing 
integer_encoded=integer_encoded.reshape(len(integer_encoded),1) # make 2D array
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [0]:
# invert first example 
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0,:])]) # how to print all??
print(inverted)

['cold']


# One Hot Encode with Keras

to_categorical() can be used to one hot encode integer data

In [0]:
from numpy import array
from numpy import argmax
from keras.utils import to_categorical
# define example 
data = [1,3,2,0,3,2,2,1,0,1]
data = array(data)
print(data)

[1 3 2 0 3 2 2 1 0 1]


In [0]:
# one hot encode 
encoded = to_categorical(data)
print(encoded)

[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [0]:
# invert encoding 
inverted = argmax(encoded[0])
print(inverted)

1
